"""Audited second-order inverse-metric responses used by the q=8 notebook.

This module contains the spatial (Stage-1) subset of the corrected harmonic
coordinate transformation:

- three spatial accelerations,
- six components of the symmetric spatial-strain rate,
- five components of the physical electric STF tensor, and
- fifteen spatial harmonic quadrupoles.

It also contains the known quadratic source generated by the first-order
time-gradient ``beta`` and spatial strain.  The formulas are transcribed from
the corrected q=4 audit notebook.
"""

from __future__ import annotations

import numpy as np
from scipy.special import spence


def orthonormal_stf_basis() -> np.ndarray:
    """Return an orthonormal Cartesian STF basis."""
    basis = [
        np.diag([1.0, -1.0, 0.0]) / np.sqrt(2.0),
        np.diag([1.0, 1.0, -2.0]) / np.sqrt(6.0),
    ]
    for i, j in ((0, 1), (0, 2), (1, 2)):
        tensor = np.zeros((3, 3))
        tensor[i, j] = tensor[j, i] = 1.0 / np.sqrt(2.0)
        basis.append(tensor)
    return np.asarray(basis)


def orthonormal_symmetric_basis() -> np.ndarray:
    """Return an orthonormal Cartesian symmetric-matrix basis."""
    basis = []
    for i in range(3):
        tensor = np.zeros((3, 3))
        tensor[i, i] = 1.0
        basis.append(tensor)
    for i, j in ((0, 1), (0, 2), (1, 2)):
        tensor = np.zeros((3, 3))
        tensor[i, j] = tensor[j, i] = 1.0 / np.sqrt(2.0)
        basis.append(tensor)
    return np.asarray(basis)


STF_BASIS = orthonormal_stf_basis()
SYMMETRIC_BASIS = orthonormal_symmetric_basis()

STAGE1_PARAMETER_NAMES = (
    tuple(f"spatial_acceleration_{axis}" for axis in "xyz")
    + tuple(
        f"spatial_strain_rate_basis_{index}"
        for index in range(6)
    )
    + tuple(
        f"electric_stf_basis_{index}" for index in range(5)
    )
    + tuple(
        f"spatial_quadrupole_{axis}_basis_{index}"
        for axis in "xyz" for index in range(5)
    )
)

STAGE1_GROUP_SLICES = {
    "spatial acceleration": slice(0, 3),
    "symmetric spatial-strain rate": slice(3, 9),
    "physical electric STF": slice(9, 14),
    "spatial harmonic quadrupole": slice(14, 29),
}

FULL_PARAMETER_NAMES = (
    STAGE1_PARAMETER_NAMES
    + ("time_acceleration",)
    + tuple(
        f"time_gradient_rate_{axis}" for axis in "xyz"
    )
    + tuple(
        f"time_quadrupole_basis_{index}"
        for index in range(5)
    )
    + tuple(
        f"magnetic_stf_basis_{index}"
        for index in range(5)
    )
)

FULL_GROUP_SLICES = {
    **STAGE1_GROUP_SLICES,
    "time acceleration": slice(29, 30),
    "time-gradient rate": slice(30, 33),
    "time harmonic quadrupole": slice(33, 38),
    "physical magnetic STF": slice(38, 43),
}

STAGE1_INDICES = np.arange(0, 29)
STAGE2_INDICES = np.arange(29, 38)
STAGE3_INDICES = np.arange(38, 43)


def radial_functions(mass: float, radius: float) -> dict[str, float]:
    """Return harmonic-Schwarzschild radial functions and derivatives."""
    areal_radius = radius + mass
    f = 1.0 - 2.0 * mass / areal_radius
    F = 1.0 + 2.0 * mass / areal_radius
    H = 4.0 * mass**2 / areal_radius**2
    g_perpendicular = radius**2 / areal_radius**2
    g_parallel = -mass**2 / areal_radius**2
    background_tt = f * F**2 - 2.0 * F
    background_tt_prime = (
        2.0 * mass / areal_radius**2
        + 8.0 * mass**2 / areal_radius**3
        + 24.0 * mass**3 / areal_radius**4
    )
    background_tt_second = (
        -4.0 * mass / areal_radius**3
        - 24.0 * mass**2 / areal_radius**4
        - 96.0 * mass**3 / areal_radius**5
    )
    H_prime = -8.0 * mass**2 / areal_radius**3
    H_second = 24.0 * mass**2 / areal_radius**4
    g_perpendicular_prime = (
        2.0 * mass * radius / areal_radius**3
    )
    g_perpendicular_second = (
        2.0 * mass * (mass - 2.0 * radius)
        / areal_radius**4
    )
    g_parallel_prime = 2.0 * mass**2 / areal_radius**3
    g_parallel_second = -6.0 * mass**2 / areal_radius**4
    return {
        "areal_radius": areal_radius,
        "f": f,
        "F": F,
        "H": H,
        "g_perpendicular": g_perpendicular,
        "g_parallel": g_parallel,
        "background_tt": background_tt,
        "background_tt_prime": background_tt_prime,
        "background_tt_second": background_tt_second,
        "H_prime": H_prime,
        "H_second": H_second,
        "g_perpendicular_prime": g_perpendicular_prime,
        "g_perpendicular_second": g_perpendicular_second,
        "g_parallel_prime": g_parallel_prime,
        "g_parallel_second": g_parallel_second,
    }


def acceleration_profile(
    mass: float, radius: float
) -> tuple[float, float]:
    """Return J and dJ/drho in xi_(2)^mu = J ddot(q)^mu."""
    areal_radius = radius + mass
    x = areal_radius / (2.0 * mass)
    tortoise_radius = (
        areal_radius + 2.0 * mass * np.log(x)
    )
    tortoise_prime = 1.0 + 2.0 * mass / areal_radius
    dhesi_profile = (
        -4.0 * mass**2 * spence(x)
        + (
            (3.0 * radius + 14.0 * mass) * tortoise_radius
            - (
                radius**2
                + 8.0 * mass * radius
                + 25.0 * mass**2
            )
        )
        / 3.0
    )
    dhesi_profile_prime = (
        4.0 * mass**2 * np.log(x) / (radius - mass)
        + (
            3.0 * tortoise_radius
            + (3.0 * radius + 14.0 * mass) * tortoise_prime
            - (2.0 * radius + 8.0 * mass)
        )
        / 3.0
    )
    return (
        dhesi_profile - 0.5 * tortoise_radius**2,
        dhesi_profile_prime
        - tortoise_radius * tortoise_prime,
    )


def matrix_to_metric_tuple(
    metric: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert arrays of 4x4 inverse metrics to (GTT, GTI, GIJ)."""
    metric = np.asarray(metric)
    return (
        metric[..., 0, 0],
        metric[..., 0, 1:],
        metric[..., 1:, 1:],
    )


def acceleration_response_at_direction(
    mass: float,
    radius: float,
    direction: np.ndarray,
    acceleration: np.ndarray,
) -> np.ndarray:
    """Return the response linear in harmonic-time acceleration."""
    radial = radial_functions(mass, radius)
    J, J_prime = acceleration_profile(mass, radius)
    time_acceleration = acceleration[0]
    spatial_acceleration = acceleration[1:]
    radial_acceleration = spatial_acceleration @ direction
    response = np.zeros((4, 4))
    response[0, 0] = (
        2.0 * radial["H"] * J_prime * time_acceleration
        - J
        * radial["background_tt_prime"]
        * radial_acceleration
    )
    response_ti = (
        radial["H"] * J_prime * spatial_acceleration
        + radial["f"]
        * J_prime
        * time_acceleration
        * direction
        - J
        * radial["H_prime"]
        * radial_acceleration
        * direction
        - J
        * radial["H"]
        / radius
        * (
            spatial_acceleration
            - radial_acceleration * direction
        )
    )
    response[0, 1:] = response[1:, 0] = response_ti
    symmetric_direction_acceleration = 0.5 * (
        np.outer(direction, spatial_acceleration)
        + np.outer(spatial_acceleration, direction)
    )
    response[1:, 1:] = (
        2.0
        * radial["f"]
        * J_prime
        * symmetric_direction_acceleration
        - J
        * radial["g_perpendicular_prime"]
        * radial_acceleration
        * np.eye(3)
        - J
        * radial["g_parallel_prime"]
        * radial_acceleration
        * np.outer(direction, direction)
        - 2.0
        * J
        * radial["g_parallel"]
        / radius
        * (
            symmetric_direction_acceleration
            - radial_acceleration
            * np.outer(direction, direction)
        )
    )
    return response


def strain_rate_response_at_direction(
    mass: float,
    radius: float,
    direction: np.ndarray,
    spatial_strain_rate: np.ndarray,
) -> np.ndarray:
    """Return the response linear in dot(c^i_11j)."""
    radial = radial_functions(mass, radius)
    K = -2.0 * (radius - 2.0 * mass)
    K_prime = -2.0
    gamma = spatial_strain_rate @ direction
    gamma_radial = direction @ gamma
    symmetric_strain_rate = 0.5 * (
        spatial_strain_rate + spatial_strain_rate.T
    )
    response = np.zeros((4, 4))
    response[0, 0] = (
        -K
        * radial["background_tt_prime"]
        * gamma_radial
    )
    response_ti = (
        radial["background_tt"]
        * (radius / mass)
        * gamma
        + radial["H"] * K_prime * gamma
        - K
        * radial["H_prime"]
        * gamma_radial
        * direction
        - K
        * radial["H"]
        / radius
        * (gamma - gamma_radial * direction)
    )
    response[0, 1:] = response[1:, 0] = response_ti
    symmetric_direction_gamma = 0.5 * (
        np.outer(direction, gamma)
        + np.outer(gamma, direction)
    )
    response[1:, 1:] = (
        2.0
        * radial["H"]
        * (radius / mass)
        * symmetric_direction_gamma
        + 2.0
        * radial["f"]
        * K_prime
        * symmetric_direction_gamma
        + 2.0
        * radial["g_perpendicular"]
        * K
        / radius
        * (
            symmetric_strain_rate
            - symmetric_direction_gamma
        )
        - K
        * radial["g_perpendicular_prime"]
        * gamma_radial
        * np.eye(3)
        - K
        * radial["g_parallel_prime"]
        * gamma_radial
        * np.outer(direction, direction)
        - 2.0
        * K
        * radial["g_parallel"]
        / radius
        * (
            symmetric_direction_gamma
            - gamma_radial * np.outer(direction, direction)
        )
    )
    return response


def time_gradient_rate_response_at_direction(
    mass: float,
    radius: float,
    direction: np.ndarray,
    time_gradient_rate: np.ndarray,
) -> np.ndarray:
    """Return the response linear in dot(c^0_11i)."""
    radial = radial_functions(mass, radius)
    K = -2.0 * (radius - 2.0 * mass)
    K_prime = -2.0
    beta = time_gradient_rate @ direction
    response = np.zeros((4, 4))
    response[0, 0] = (
        2.0
        * radial["background_tt"]
        * (radius / mass)
        * beta
        + 2.0 * radial["H"] * K_prime * beta
    )
    response_ti = (
        radial["H"]
        * (radius / mass)
        * beta
        * direction
        + radial["f"] * K_prime * beta * direction
        + radial["g_perpendicular"]
        * K
        / radius
        * (time_gradient_rate - beta * direction)
    )
    response[0, 1:] = response[1:, 0] = response_ti
    return response


def electric_response_at_direction(
    mass: float,
    radius: float,
    direction: np.ndarray,
    electric_stf: np.ndarray,
) -> np.ndarray:
    """Return the complete response to the physical electric STF tensor."""
    radial = radial_functions(mass, radius)
    areal_radius = radial["areal_radius"]
    electric_scalar = direction @ electric_stf @ direction
    electric_vector = electric_stf @ direction
    electric_transverse = (
        electric_vector - electric_scalar * direction
    )
    projector = np.eye(3) - np.outer(direction, direction)

    time_profile = -mass * (radius**2 - mass**2)
    time_profile_prime = -2.0 * mass * radius
    alpha1 = (
        0.25
        * mass
        * (radius**2 - mass**2)
        * (3.0 * radius + mass)
    )
    alpha1_prime = 0.25 * mass * (
        2.0 * radius * (3.0 * radius + mass)
        + 3.0 * (radius**2 - mass**2)
    )
    alpha3 = (
        (radius**2 - mass**2)
        * (
            5.0 * radius**2
            + 2.0 * mass * radius
            - mass**2
        )
        / 6.0
    )
    alpha3_prime = (
        2.0
        * radius
        * (
            5.0 * radius**2
            + 2.0 * mass * radius
            - mass**2
        )
        + (radius**2 - mass**2)
        * (10.0 * radius + 2.0 * mass)
    ) / 6.0
    vector_profile = 0.4 * (alpha1 - alpha3)
    vector_profile_prime = 0.4 * (
        alpha1_prime - alpha3_prime
    )
    radial_profile = alpha3
    radial_profile_prime = alpha3_prime
    radial_displacement = (
        vector_profile + radial_profile
    ) * electric_scalar
    transverse_displacement = (
        vector_profile * electric_transverse
    )

    response = np.zeros((4, 4))
    response[0, 0] = (
        2.0
        * radial["H"]
        * time_profile_prime
        * electric_scalar
        - radial["background_tt_prime"]
        * radial_displacement
        + areal_radius**2
        * electric_scalar
        * (
            -1.0
            + radial["f"] * radial["F"]
            - 0.5 * (radial["f"] * radial["F"]) ** 2
        )
    )
    response_ti = (
        radial["f"]
        * time_profile_prime
        * electric_scalar
        * direction
        + 2.0
        * radial["g_perpendicular"]
        * time_profile
        / radius
        * electric_transverse
        + radial["H"]
        * (
            vector_profile_prime * electric_vector
            + radial_profile_prime
            * electric_scalar
            * direction
        )
        - radial["H_prime"]
        * radial_displacement
        * direction
        - radial["H"] / radius * transverse_displacement
        - 2.0
        * mass**2
        * radial["f"]
        * electric_scalar
        * direction
    )
    response[0, 1:] = response[1:, 0] = response_ti
    symmetric_direction_electric = 0.5 * (
        np.outer(direction, electric_vector)
        + np.outer(electric_vector, direction)
    )
    symmetric_transverse_direction = 0.5 * (
        np.outer(transverse_displacement, direction)
        + np.outer(direction, transverse_displacement)
    )
    response[1:, 1:] = (
        2.0
        * radial["f"]
        * vector_profile_prime
        * symmetric_direction_electric
        + 2.0
        * radial["f"]
        * radial_profile_prime
        * electric_scalar
        * np.outer(direction, direction)
        + 2.0
        * radial["g_perpendicular"]
        * vector_profile
        / radius
        * (electric_stf - symmetric_direction_electric)
        + 4.0
        * radial["g_perpendicular"]
        * radial_profile
        / radius
        * (
            symmetric_direction_electric
            - electric_scalar * np.outer(direction, direction)
        )
        + 2.0
        * radial["g_perpendicular"]
        * radial_profile
        * electric_scalar
        / radius
        * projector
        - radial_displacement
        * (
            radial["g_perpendicular_prime"] * np.eye(3)
            + radial["g_parallel_prime"]
            * np.outer(direction, direction)
        )
        - 2.0
        * radial["g_parallel"]
        / radius
        * symmetric_transverse_direction
        - 0.5
        * areal_radius**2
        * radial["f"] ** 2
        * electric_scalar
        * np.outer(direction, direction)
        - 0.5
        * radius**2
        * (areal_radius**2 - 2.0 * mass**2)
        / areal_radius**2
        * electric_scalar
        * projector
    )
    return response


def spatial_quadrupole_response_at_direction(
    mass: float,
    radius: float,
    direction: np.ndarray,
    spatial_quadrupole: np.ndarray,
) -> np.ndarray:
    """Return the response to c^i_22jk, STF in j,k."""
    radial = radial_functions(mass, radius)
    phi = 0.5 * (3.0 * (radius / mass) ** 2 - 1.0)
    phi_prime = 3.0 * radius / mass**2
    quadrupole_vector = np.einsum(
        "ijk,j,k->i",
        spatial_quadrupole,
        direction,
        direction,
    )
    one_contraction = np.einsum(
        "ijk,k->ij", spatial_quadrupole, direction
    )
    radial_quadrupole = direction @ quadrupole_vector
    transverse_quadrupole = (
        quadrupole_vector - radial_quadrupole * direction
    )
    radial_displacement = phi * radial_quadrupole
    transverse_displacement = phi * transverse_quadrupole
    response = np.zeros((4, 4))
    response[0, 0] = (
        -radial_displacement
        * radial["background_tt_prime"]
    )
    response[0, 1:] = response[1:, 0] = (
        radial["H"] * phi_prime * quadrupole_vector
        - phi
        * radial_quadrupole
        * radial["H_prime"]
        * direction
        - radial["H"] / radius * transverse_displacement
    )
    symmetric_quadrupole_direction = 0.5 * (
        np.outer(quadrupole_vector, direction)
        + np.outer(direction, quadrupole_vector)
    )
    response[1:, 1:] = (
        2.0
        * radial["f"]
        * phi_prime
        * symmetric_quadrupole_direction
        + 4.0
        * radius
        * phi
        / radial["areal_radius"] ** 2
        * (
            0.5
            * (one_contraction + one_contraction.T)
            - symmetric_quadrupole_direction
        )
        - radial_displacement
        * (
            radial["g_perpendicular_prime"] * np.eye(3)
            + radial["g_parallel_prime"]
            * np.outer(direction, direction)
        )
        - 2.0
        * radial["g_parallel"]
        / radius
        * 0.5
        * (
            np.outer(transverse_displacement, direction)
            + np.outer(direction, transverse_displacement)
        )
    )
    return response


def time_quadrupole_response_at_direction(
    mass: float,
    radius: float,
    direction: np.ndarray,
    time_quadrupole: np.ndarray,
) -> np.ndarray:
    """Return the response to the STF time-coordinate quadrupole."""
    radial = radial_functions(mass, radius)
    phi = 0.5 * (3.0 * (radius / mass) ** 2 - 1.0)
    phi_prime = 3.0 * radius / mass**2
    quadrupole_scalar = (
        direction @ time_quadrupole @ direction
    )
    quadrupole_vector = time_quadrupole @ direction
    response = np.zeros((4, 4))
    response[0, 0] = (
        2.0
        * radial["H"]
        * phi_prime
        * quadrupole_scalar
    )
    response[0, 1:] = response[1:, 0] = (
        radial["f"]
        * phi_prime
        * quadrupole_scalar
        * direction
        + 2.0
        * radius
        * phi
        / radial["areal_radius"] ** 2
        * (
            quadrupole_vector
            - quadrupole_scalar * direction
        )
    )
    return response


def magnetic_response_at_direction(
    mass: float,
    radius: float,
    direction: np.ndarray,
    magnetic_stf: np.ndarray,
) -> np.ndarray:
    """Return the direct response to the physical magnetic STF tensor."""
    response = np.zeros((4, 4))
    response[0, 1:] = response[1:, 0] = (
        -2.0
        * (radius + mass)
        * radius
        * np.cross(direction, magnetic_stf @ direction)
    )
    return response


def stage1_response_columns_at_points(
    points: np.ndarray, mass: float
) -> tuple[tuple[np.ndarray, np.ndarray, np.ndarray], ...]:
    """Return the 29 Stage-1 response fields at arbitrary points."""
    points = np.asarray(points)
    radii = np.linalg.norm(points, axis=1)
    directions = points / radii[:, None]
    response_builders = []

    for component in range(3):
        acceleration = np.zeros(4)
        acceleration[1 + component] = 1.0
        response_builders.append(
            lambda radius, direction, acceleration=acceleration:
            acceleration_response_at_direction(
                mass, radius, direction, acceleration
            )
        )
    for basis in SYMMETRIC_BASIS:
        response_builders.append(
            lambda radius, direction, basis=basis:
            strain_rate_response_at_direction(
                mass, radius, direction, basis
            )
        )
    for basis in STF_BASIS:
        response_builders.append(
            lambda radius, direction, basis=basis:
            electric_response_at_direction(
                mass, radius, direction, basis
            )
        )
    for spatial_component in range(3):
        for basis in STF_BASIS:
            quadrupole = np.zeros((3, 3, 3))
            quadrupole[spatial_component] = basis
            response_builders.append(
                lambda radius, direction,
                quadrupole=quadrupole:
                spatial_quadrupole_response_at_direction(
                    mass, radius, direction, quadrupole
                )
            )

    columns = []
    for builder in response_builders:
        matrices = np.asarray([
            builder(radius, direction)
            for radius, direction in zip(radii, directions)
        ])
        columns.append(matrix_to_metric_tuple(matrices))
    assert len(columns) == 29
    return tuple(columns)


def full_response_columns_at_points(
    points: np.ndarray, mass: float
) -> tuple[tuple[np.ndarray, np.ndarray, np.ndarray], ...]:
    """Return all 43 minimal nonrotating response fields."""
    points = np.asarray(points)
    radii = np.linalg.norm(points, axis=1)
    directions = points / radii[:, None]
    columns = list(stage1_response_columns_at_points(
        points, mass
    ))
    response_builders = []

    time_acceleration = np.zeros(4)
    time_acceleration[0] = 1.0
    response_builders.append(
        lambda radius, direction:
        acceleration_response_at_direction(
            mass, radius, direction, time_acceleration
        )
    )
    for component in range(3):
        time_gradient_rate = np.zeros(3)
        time_gradient_rate[component] = 1.0
        response_builders.append(
            lambda radius, direction,
            time_gradient_rate=time_gradient_rate:
            time_gradient_rate_response_at_direction(
                mass,
                radius,
                direction,
                time_gradient_rate,
            )
        )
    for basis in STF_BASIS:
        response_builders.append(
            lambda radius, direction, basis=basis:
            time_quadrupole_response_at_direction(
                mass, radius, direction, basis
            )
        )
    for basis in STF_BASIS:
        response_builders.append(
            lambda radius, direction, basis=basis:
            magnetic_response_at_direction(
                mass, radius, direction, basis
            )
        )

    for builder in response_builders:
        matrices = np.asarray([
            builder(radius, direction)
            for radius, direction in zip(radii, directions)
        ])
        columns.append(matrix_to_metric_tuple(matrices))
    assert len(columns) == 43
    return tuple(columns)


def known_quadratic_first_order_source(
    points: np.ndarray,
    beta: np.ndarray,
    spatial_strain: np.ndarray,
    mass: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return the known beta^2, beta-Lambda, and Lambda^2 source."""
    points = np.asarray(points)
    radius = np.linalg.norm(points, axis=1)
    direction = points / radius[:, None]
    source_tt = np.zeros(len(points))
    source_ti = np.zeros((len(points), 3))
    source_ij = np.zeros((len(points), 3, 3))

    for point_index, (rho, n) in enumerate(zip(radius, direction)):
        radial = radial_functions(mass, rho)
        beta_radial = beta @ n
        strain_vector = spatial_strain @ n
        strain_scalar = n @ strain_vector
        transverse_strain = (
            strain_scalar * n - strain_vector
        )
        beta_transverse_strain = beta @ transverse_strain

        source_tt[point_index] += (
            radial["g_perpendicular"] * (beta @ beta)
            + radial["g_parallel"] * beta_radial**2
        )

        w0 = (
            radial["g_perpendicular"] * beta
            + radial["g_parallel"] * beta_radial * n
        )
        w1 = (
            -rho
            * strain_scalar
            * radial["g_perpendicular_prime"]
            * beta
            - rho
            * strain_scalar
            * radial["g_parallel_prime"]
            * beta_radial
            * n
            + radial["g_parallel"]
            * (
                beta_radial * transverse_strain
                + beta_transverse_strain * n
            )
        )
        source_tt[point_index] += (
            2.0
            * radial["H"]
            * beta_transverse_strain
            - 2.0
            * rho
            * strain_scalar
            * radial["H_prime"]
            * beta_radial
        )
        source_ti[point_index] += spatial_strain @ w0 + w1

        strain_squared_vector = (
            spatial_strain @ spatial_strain @ n
        )
        mu = n @ strain_squared_vector
        d2 = (
            mu
            + 0.5
            * (
                strain_vector @ strain_vector
                - strain_scalar**2
            )
        )
        symmetric_strain = (
            spatial_strain + spatial_strain.T
        )
        strain_product = spatial_strain @ spatial_strain.T
        source_tt[point_index] += (
            rho * d2 * radial["background_tt_prime"]
            + 0.5
            * rho**2
            * strain_scalar**2
            * radial["background_tt_second"]
        )
        source_ti[point_index] += (
            d2
            * (rho * radial["H_prime"] - radial["H"])
            + strain_scalar**2
            * (
                radial["H"]
                - rho * radial["H_prime"]
                + 0.5 * rho**2 * radial["H_second"]
            )
        ) * n
        source_ij[point_index] += (
            (
                rho
                * d2
                * radial["g_perpendicular_prime"]
                + 0.5
                * rho**2
                * strain_scalar**2
                * radial["g_perpendicular_second"]
            )
            * np.eye(3)
            - rho
            * strain_scalar
            * radial["g_perpendicular_prime"]
            * symmetric_strain
            + radial["g_perpendicular"] * strain_product
            + (
                d2
                * (
                    rho * radial["g_parallel_prime"]
                    - 2.0 * radial["g_parallel"]
                )
                + strain_scalar**2
                * (
                    0.5
                    * rho**2
                    * radial["g_parallel_second"]
                    - 2.0
                    * rho
                    * radial["g_parallel_prime"]
                    + 3.0 * radial["g_parallel"]
                )
            )
            * np.outer(n, n)
        )

    return source_tt, source_ti, source_ij
